name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install pytest
      - 
        run: pip install pylint

      - name: Run tests
        run: pytest

      - name: Make a Report
        run: pylint calculator.py || true
